[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1MbvWpJNs1TpQVkXnFw5HetFgBEyOCUKgA3G_pZh4mgo"
spreadsheet_id = "1MbvWpJNs1TpQVkXnFw5HetFgBEyOCUKgA3G_pZh4mgo"
type= "service_account"
project_id= "dashboard-financas"
private_key_id= "62f6a0dd136ba2c151b906a33fea85e1902e6fda"
private_key= "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCiVoD/d7yTDsWe\ntAYPx4I8QvLrzqdITrCESO2GSx8kf278GciQu5MvgMylp2k3eEgxdis+0F/Wui6+\ntpSeZHxARywKwmLwjvNjh6i+M/tIJ7h8rVJ+0pZiE4PhQXYFRfXJV7yKPSpMR9K/\npp+CRsj3DxyveS+NEsWE0AC/kDH/AL4CeQMpBRhHjXBrJfWo6RQB0H0X52xEWPXq\nxRgeDFuqapSApT3uIhYH/5r/6a8d3JKqVnZTFJVQHsxiXRdVGhrORn0SorFFboKz\ndziu+eGrUyQFMquNtlCXmNg9ufOjEAc/Uaxdb36UNh96zVfECJmgXTsOK80loQXZ\nJPVuLlX5AgMBAAECggEARscbYAa255D5tWt89xU/oYF5Azmq8pooWMypDrOjBNkw\nrOaa7QtzLTNlRlY6yA3/v9zrFuxn1KmBJvJY0sQx7h55w8kjtQlGcZ8cga0NQlTb\nGTTCMnwjR+iFR8kwKTVq55mCoOzxC6gG6Ts+8WBmT1093v2hr0q/Zlv/74VxXuGk\nsoJZf8fNfxgp4gdQ7g9wiEnwByBLbAH4fFZa/+A8rSxR17vzeMsCxZo2hNkBgJkX\n1wrMhr+bOUqFsdF7/JrDSjJ6PLs8yqFIOx8pgxoateuTfFsNtbDw/v+WOa7eECrm\nZ+dpFBJ09jifJYpmLNA5DJoddt557h4gcLAL4J3ZXwKBgQDMkR9zX7t0AYgkH5E8\nUAGvhqeTNk4V3trdeBLF7EYkOm84wjx7SXIO7wRBPJJJvNcTqaDA6dGYsybiNSHq\n8KhISflKlSp0tTqJBxJ5JIxJqNrENVdw6D9OTunl0sg2oNcR3UbtFzCsO/vEeGju\nLcgLGhHaRv0RsXKuTrN/psGuDwKBgQDLJ1PIZjU+RbE2+GMaX6kPvK4IhGV9Qmih\nAz07l6dGZDIlCHSjedywg264F03Aq1s5ZXhKq0cHFmoo+D+YumBBBZP+njrR7QH/\nLgcAN0Z7wZDseW8iScTgn8o4wC7GsqnuSNGOKM395PqFdREpBPtQzPt0n4dsMtXi\nwd/0hV/DdwKBgHU28n55bD+cYRXRwLZ+YXjh/0Mq6rM9bstX8enW6Jn5oaE0KtO5\n0dEcw6NdwbTer55ko+fmEmMcxDr5luW337UMLfu+XQVikpfRpZQkjP3n8vJaXjAj\n46JLNVqq3G3w20sxL2LK1ujZtfltxTI0qVszJOedpYRt2PhnwBJ0yqWhAoGBAIAX\nWeJfX27WLnjEgGgerNA5XVoNcJhcCPCMxE0Qv+3IOz3SaQiyS44YMPVt7B5xbOFx\nszkRaYV0gpc2f5Li4NHenIPMbLX0RHALK2rdb1mUoLYZkxMBhFtFJRJHSrcJ689M\npqSF4ewWNkdzmtBMTdGSjXHpLE/ydZ22NGlOtyTdAoGBALWFrTRcgdc3qsPSSOfE\nVGIDv9n54treorEgsgZzp3uXbaIVp4J0bFHu5788Xeq4EaUl8tOcfOXsBRv1gZDz\nYzBk0lTnrItB4YHAzmvbYCPa4Bfh4RkzUyqWW/NJXCy8EDxMFdVTiqsS9P/tElo3\n8mU0v70AUQ1y8ORR5LzX2nOk\n-----END PRIVATE KEY-----\n"
client_email= "python-gsheets-access@dashboard-financas.iam.gserviceaccount.com"
client_id= "107979381050300787561"
auth_uri= "https://accounts.google.com/o/oauth2/auth"
token_uri= "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url= "https://www.googleapis.com/robot/v1/metadata/x509/scoutdatabase%40scoutdatabase.iam.gserviceaccount.com"
universe_domain= "googleapis.com"

[secrets]
GOOGLE_API_KEY = "AIzaSyDdzfeIF5x4C3ZvRyuL71Ht5MRIKOfWTtQ"
GEMINI = "AIzaSyDdzfeIF5x4C3ZvRyuL71Ht5MRIKOfWTtQ"
OPENROUTER_API_KEY = "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"
GROQ_API_KEY = "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"

[GEMINI]
api_key = "AIzaSyDdzfeIF5x4C3ZvRyuL71Ht5MRIKOfWTtQ"
